---
BedFile: ex/markers.txt.bed
isPcrBinary: isPcr
TwoBitFile: hg38.2bit
MpdBinary: ../mpd-c/build/mpd
MpdIdx: hg38.d14.sdx
dbSnpIdx: ds_flat.sdx

CoverageThreshold: 0.8
PrimerSizeMin: 17
PrimerSizeMax: 27
PadSize: 60
PoolMax: 10
PoolMin: 5

AmpSizeMax: 260
AmpSizeMin: 230
TmMax: 62
TmMin: 57
GcMax: 0.7
GcMin: 0.3

Iter: 2
IncrTm: 1
IncrTmStep: 1
IncrAmpSize: 10
